name: Update Doc on Github Page

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - '.github/workflows/publish-package.yml'

concurrency:
  group: doc
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
        env:
          PUBLIC_ASTRO_BASE: /design-systems
      - name: Deploy doc to Github Page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/dist
